const GETGENRES = "GETGENRES";
const GETALLVIDEOGAMES = "GETALLVIDEOGAMES";
const GETVIDEOGAMESBYNAME = "GETVIDEOGAMESBYNAME";
const GETVIDEOGAMEBYID = "GETVIDEOGAMEBYID";
const POSTVIDEOGAME = "POSTVIDEOGAME";
const MODIFYPAGE = "MODIFYPAGE";
const TOPPAGE = "TOPPAGE";
const BOTTOMPAGE = "BOTTOMPAGE";

//alphabetic, genres, origin, rating
const RESET = "RESET";
const ALPHABETICORDER = "ALPHABETICORDER";
const RATINGORDER = "RATINGORDER";
const FILTERBYGENRES = "FILTERBYGENRES";
const FILTERBYORIGIN = "FILTERBYORIGIN";

export {
  GETGENRES,
  GETALLVIDEOGAMES,
  GETVIDEOGAMESBYNAME,
  GETVIDEOGAMEBYID,
  POSTVIDEOGAME,
  MODIFYPAGE,
  TOPPAGE,
  BOTTOMPAGE,
  RESET,
  ALPHABETICORDER,
  RATINGORDER,
  FILTERBYGENRES,
  FILTERBYORIGIN,
};
